***NumPy***

[40, 980, -200]
[4.0, 49.0, 4.0]
-3.5964912280701755


Importing numpy

In [ ]:
import numpy as np

The main object in numpy is the ndarray(N dimensional array) and it is multidimensional and homogenous array with predetermined number of items. All the items present in the array are of same type and size. The data type is specified by another object called dtype(data-type). The number of dimensions and items are defined by its shape, a tuple of N-dimensional items specifies the size for each dimension. The dimensions are defined as axes and the number of axes as rank.
Also the size of the array is fixed from the time of creation and doesn't change.  

Defining a ndarray using array() function

In [ ]:
a = np.array([1,4,9,16])
print(a)

[ 1  4  9 16]


Check the type using type() function.

In [ ]:
type(a)

numpy.ndarray

We can easily check the datatype of the array using dtype attribute.

In [ ]:
a.dtype

dtype('int64')

The created has 1 axis and its rank is 1, while its shape is [3,1]. Using ndim we can get the axes and size to determine the length of the array and shape to get the shape.

In [ ]:
a.ndim


1

In [ ]:
a.size

4

In [ ]:
a.shape

(4,)

Defining a two dimensional array 2x2.

In [ ]:
b=np.array([[1.0,5],[6,5]])
print(b)

[[1. 5.]
 [6. 5.]]


In [ ]:
b.ndim

2

In [ ]:
b.size

4

In [ ]:
b.shape

(2, 2)

In [ ]:
b.dtype

dtype('float64')

Itemsize returns the size in bytes of each element.

In [ ]:
b.itemsize

8

The array() function in addition to lists can also accept tuples.

In [ ]:
c=np.array(((1,2,3),(4,5,6)))
print(c)

[[1 2 3]
 [4 5 6]]


It can also accept both tuples and lists.

In [ ]:
d=np.array([[1,2,3],(4,5,6),[7,8,9]])
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array also accepts a various types of data such as strings.

In [ ]:
e=np.array([['g','f'],['r','f']])
print(e)

[['g' 'f']
 ['r' 'f']]


In [ ]:
e.dtype

dtype('<U1')

In [ ]:
e.dtype.name

'str32'

Generally array function associates a suitable datatype with the given input but we can explicitly give the dtype with dtype argument to the array function.

In [ ]:
f=np.array([[1,2,5],[6,7,9]], dtype='complex64')
print(f)

[[1.+0.j 2.+0.j 5.+0.j]
 [6.+0.j 7.+0.j 9.+0.j]]


The numpy also have a lot of function with initial data.

zeros() function

In [ ]:
g=np.zeros((5,3))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


ones() function

In [ ]:
h=np.ones((6,4))
print(h)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


By default both of them are created with float64 dtype.

eye creates a identity matrix and takes a single input and full creates an array ones with a constant multiplied

In [ ]:
print(np.eye(4))
print(np.full((3,3),5))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


diag() function returns the diagonal elements of a 2d array and diag(v,0) creates a diagonal matrix with array v as diagonal elements.

In [ ]:
v=np.arange(5,8)
A=np.diag(v,0)
print(A)
print(np.diag(A))

[[5 0 0]
 [0 6 0]
 [0 0 7]]
[5 6 7]


arange() function accepts two inputs generating a row vector depending on the inputs.


In [ ]:
i=np.arange(0,10)
print(i)
j=np.arange(6,13)
print(j)
k=np.arange(0,12,4) # float can also be used
print(k)

[0 1 2 3 4 5 6 7 8 9]
[ 6  7  8  9 10 11 12]
[0 4 8]


The one dimensional array can also shaped to other dimensions using reshape function.

In [ ]:
l=np.arange(0,10).reshape(2,5)
print(l)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Another function similar to arange is the linspace function but third input is used to specify the number of elements in the array.

In [ ]:
m=np.linspace(0,10,101)
print(m)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


You can also generate random values using the random function in numpy.


In [ ]:
n=np.random.random((3,4))
print(n)

[[0.67516987 0.66045757 0.59689085 0.3837008 ]
 [0.49415384 0.26748341 0.77522149 0.78552308]
 [0.75975103 0.01399215 0.05726414 0.38597743]]


Arthimetic operations in arrays. The * means elementwise operations in array and adding or multiplying a scalar simply means elementwise operations.

In [ ]:
a1=np.array([2,5,8,10])
b1=a1+4
c1=a1*4
d1=np.array([1,2,3,4])
a2=a1*d1 # you can also use multiply function here as well as add, divide, subtract functions depending on the use case
print(b1,c1,a2)

[ 6  9 12 14] [ 8 20 32 40] [ 2 10 24 40]


To get the matrix multiplication use dot function. You can also use @ operator

In [ ]:
A=np.linspace(0,2,3) #row vector
B=np.ones((3,1))
C=np.dot(A,B)
D=A.dot(B) # alternate
E=A@B # alternate
print(C,D,E)

[3.] [3.] [3.]


The same increment and decrement operators works here such as +=, -=, *=.

Universal Functions(ufunc) which operates element-by-element operations on array such log, sin, sqrt, etc. While the aggregate functions perform an operation on set of values an array and provide a single output examples include sum, min, max, mean and standard deviation.

Indexing uses square brackets to retrieve the elements for 2 dimensional arrays indexing is similar to index in matrix elements.

In [ ]:
E=np.arange(1,10).reshape(3,3)
print(E)
print(E[0,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3


Slicing for 1d array is similar to slicing in lists. We will see some examples for 2d arrays.

In [ ]:
print(E[0,:]) #returns the 1st row
print(E[:,0]) #returns the 1st column
print(E[1:3,1:3])
print(E[[0,2],0:2]) #you can also select different elements from different rows you can see that using slicing we get a higher rank array than using indexing.

[1 2 3]
[1 4 7]
[[5 6]
 [8 9]]
[[1 2]
 [7 8]]


Iterating a 1d array is similar to list and for loop to return rows. For element wise iteration use A.flat

In [ ]:

for row in E:
  print(row)
for element in E.flat:
  print(element)

[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9


For applying aggregrate function for columns or rows use apply_along_axis() function when axis=0 it operates on column and when axis=1 it operates on row.

In [ ]:
np.apply_along_axis(np.mean,axis=0,arr=E)

array([4., 5., 6.])

In [ ]:
np.apply_along_axis(np.mean,axis=1,arr=E)

array([2., 5., 8.])

In [ ]:
def half(x):
  return x/2
np.apply_along_axis(half,axis=0,arr=E)

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

Boolean Arrays

In [ ]:
H=np.random.random((4,4))
H<0.5


array([[False, False,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True, False],
       [False,  True, False, False]])

In [ ]:
H[H<0.5]

array([0.19089248, 0.10771118, 0.34072423, 0.1496796 , 0.37479061,
       0.30855878, 0.48009012])

In [ ]:
a=np.random.random(12)
print(a.reshape(3,4))
print(a) #note it doesn't change the shape of the original object

[[0.04352542 0.61805668 0.40635855 0.25896956]
 [0.10832257 0.87094763 0.04471017 0.50963639]
 [0.06463342 0.01331789 0.05844807 0.93016782]]
[0.04352542 0.61805668 0.40635855 0.25896956 0.10832257 0.87094763
 0.04471017 0.50963639 0.06463342 0.01331789 0.05844807 0.93016782]


To modify the shape of the object use shape() and a 2d array can be converted back to id array using ravel() function.

In [ ]:
a.shape=(3,4)
print(a)
a=a.ravel()
print(a)


[[0.04352542 0.61805668 0.40635855 0.25896956]
 [0.10832257 0.87094763 0.04471017 0.50963639]
 [0.06463342 0.01331789 0.05844807 0.93016782]]
[0.04352542 0.61805668 0.40635855 0.25896956 0.10832257 0.87094763
 0.04471017 0.50963639 0.06463342 0.01331789 0.05844807 0.93016782]


In [ ]:
a.shape=(3,4)
a.shape=(a.size)
print(a)

[0.04352542 0.61805668 0.40635855 0.25896956 0.10832257 0.87094763
 0.04471017 0.50963639 0.06463342 0.01331789 0.05844807 0.93016782]


Transpose of a matrix using transpose() function.

In [ ]:
E.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Norm of a vector usig

Numpy uses the horizontal stacking hstack() to stack new array as columns while the vertical stacking vstack as rows.

In [ ]:
A1=np.ones((3,3))
A2=np.zeros((3,3))
np.vstack((A1,A2)) # You can also use concatenate function

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.hstack((A1,A2)) # use concatenate((A1,A2),1)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

column_stack and row_stack are used with 1d arrays stacking them to 2d array.

In [ ]:
d1=np.arange(0,3)
d2=np.arange(3,6)
d3=np.arange(6,9)
print(np.row_stack((d1,d2,d3)))
print(np.column_stack((d1,d2,d3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


/tmp/ipython-input-346694834.py:4: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((d1,d2,d3)))


We can also split the array with vsplit and hsplit.

In [ ]:
I=np.arange(16).reshape(4,4)
[J,K]=np.vsplit(I,2)
print(J)
print(K)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
[L,M]=np.hsplit(I,2)
print(L)
print(M)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
# You can also split into nonsymmetric parts using axis where axis=0 it will be row operation and axis=1 it will be in column operation.
[I1,I2,I3]=np.split(I,[1,3],axis=1)
print(I1)
print(I2)
print(I3)
[I4,I5,I6]=np.split(I,[1,3],axis=0)
print(I4)
print(I5)
print(I6)

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]
[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


If you assign one array to another array you are not copying a to b its just another way of calling a similarly even for slicing.

In [ ]:
a=np.array([1,2,3,4])
b=a
c=a[0:2]
print(c)
a[0]=5
print(b)
print(c)

[1 2]
[5 2 3 4]
[5 2]


If you want to get a new array use copy() function. Changing the values in original array doen't the values in new array.

In [ ]:
d=a.copy()
a[0]=10
print(d)
print(a)
# If you get the d=a then the array a is get updated after each run

[5 2 3 4]
[10  2  3  4]


Broadcasting allows an operator to operate or function to act on two or more arrays even if they are of different shape this means that not all the dimensions can be subjected to broadcasting.